// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"context"

	"github.com/Irurnnen/go-gin-template/internal/services/cat"
	"github.com/Irurnnen/go-gin-template/internal/services/hello"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCatServiceInterface creates a new instance of MockCatServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatServiceInterface {
	mock := &MockCatServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatServiceInterface is an autogenerated mock type for the CatServiceInterface type
type MockCatServiceInterface struct {
	mock.Mock
}

type MockCatServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatServiceInterface) EXPECT() *MockCatServiceInterface_Expecter {
	return &MockCatServiceInterface_Expecter{mock: &_m.Mock}
}

// CatByID provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) CatByID(ctx context.Context, id *cat.CatID) (*cat.Cat, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CatByID")
	}

	var r0 *cat.Cat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID) (*cat.Cat, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID) *cat.Cat); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cat.Cat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CatID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_CatByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatByID'
type MockCatServiceInterface_CatByID_Call struct {
	*mock.Call
}

// CatByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id *cat.CatID
func (_e *MockCatServiceInterface_Expecter) CatByID(ctx interface{}, id interface{}) *MockCatServiceInterface_CatByID_Call {
	return &MockCatServiceInterface_CatByID_Call{Call: _e.mock.On("CatByID", ctx, id)}
}

func (_c *MockCatServiceInterface_CatByID_Call) Run(run func(ctx context.Context, id *cat.CatID)) *MockCatServiceInterface_CatByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_CatByID_Call) Return(cat1 *cat.Cat, err error) *MockCatServiceInterface_CatByID_Call {
	_c.Call.Return(cat1, err)
	return _c
}

func (_c *MockCatServiceInterface_CatByID_Call) RunAndReturn(run func(ctx context.Context, id *cat.CatID) (*cat.Cat, error)) *MockCatServiceInterface_CatByID_Call {
	_c.Call.Return(run)
	return _c
}

// CatChangeStatus provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) CatChangeStatus(ctx context.Context, id *cat.CatID, status *cat.CatStatusStruct) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for CatChangeStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.CatStatusStruct) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatServiceInterface_CatChangeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatChangeStatus'
type MockCatServiceInterface_CatChangeStatus_Call struct {
	*mock.Call
}

// CatChangeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id *cat.CatID
//   - status *cat.CatStatusStruct
func (_e *MockCatServiceInterface_Expecter) CatChangeStatus(ctx interface{}, id interface{}, status interface{}) *MockCatServiceInterface_CatChangeStatus_Call {
	return &MockCatServiceInterface_CatChangeStatus_Call{Call: _e.mock.On("CatChangeStatus", ctx, id, status)}
}

func (_c *MockCatServiceInterface_CatChangeStatus_Call) Run(run func(ctx context.Context, id *cat.CatID, status *cat.CatStatusStruct)) *MockCatServiceInterface_CatChangeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		var arg2 *cat.CatStatusStruct
		if args[2] != nil {
			arg2 = args[2].(*cat.CatStatusStruct)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_CatChangeStatus_Call) Return(err error) *MockCatServiceInterface_CatChangeStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatServiceInterface_CatChangeStatus_Call) RunAndReturn(run func(ctx context.Context, id *cat.CatID, status *cat.CatStatusStruct) error) *MockCatServiceInterface_CatChangeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CatCreate provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) CatCreate(ctx context.Context, data *cat.CatCreate) (*cat.CatID, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CatCreate")
	}

	var r0 *cat.CatID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatCreate) (*cat.CatID, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatCreate) *cat.CatID); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cat.CatID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CatCreate) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_CatCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatCreate'
type MockCatServiceInterface_CatCreate_Call struct {
	*mock.Call
}

// CatCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - data *cat.CatCreate
func (_e *MockCatServiceInterface_Expecter) CatCreate(ctx interface{}, data interface{}) *MockCatServiceInterface_CatCreate_Call {
	return &MockCatServiceInterface_CatCreate_Call{Call: _e.mock.On("CatCreate", ctx, data)}
}

func (_c *MockCatServiceInterface_CatCreate_Call) Run(run func(ctx context.Context, data *cat.CatCreate)) *MockCatServiceInterface_CatCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatCreate
		if args[1] != nil {
			arg1 = args[1].(*cat.CatCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_CatCreate_Call) Return(catID *cat.CatID, err error) *MockCatServiceInterface_CatCreate_Call {
	_c.Call.Return(catID, err)
	return _c
}

func (_c *MockCatServiceInterface_CatCreate_Call) RunAndReturn(run func(ctx context.Context, data *cat.CatCreate) (*cat.CatID, error)) *MockCatServiceInterface_CatCreate_Call {
	_c.Call.Return(run)
	return _c
}

// CatDelete provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) CatDelete(ctx context.Context, id *cat.CatID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CatDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatServiceInterface_CatDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatDelete'
type MockCatServiceInterface_CatDelete_Call struct {
	*mock.Call
}

// CatDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id *cat.CatID
func (_e *MockCatServiceInterface_Expecter) CatDelete(ctx interface{}, id interface{}) *MockCatServiceInterface_CatDelete_Call {
	return &MockCatServiceInterface_CatDelete_Call{Call: _e.mock.On("CatDelete", ctx, id)}
}

func (_c *MockCatServiceInterface_CatDelete_Call) Run(run func(ctx context.Context, id *cat.CatID)) *MockCatServiceInterface_CatDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_CatDelete_Call) Return(err error) *MockCatServiceInterface_CatDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatServiceInterface_CatDelete_Call) RunAndReturn(run func(ctx context.Context, id *cat.CatID) error) *MockCatServiceInterface_CatDelete_Call {
	_c.Call.Return(run)
	return _c
}

// CatSearch provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) CatSearch(ctx context.Context, params *cat.CatSearchParams) ([]*cat.Cat, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CatSearch")
	}

	var r0 []*cat.Cat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatSearchParams) ([]*cat.Cat, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatSearchParams) []*cat.Cat); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*cat.Cat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CatSearchParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_CatSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatSearch'
type MockCatServiceInterface_CatSearch_Call struct {
	*mock.Call
}

// CatSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - params *cat.CatSearchParams
func (_e *MockCatServiceInterface_Expecter) CatSearch(ctx interface{}, params interface{}) *MockCatServiceInterface_CatSearch_Call {
	return &MockCatServiceInterface_CatSearch_Call{Call: _e.mock.On("CatSearch", ctx, params)}
}

func (_c *MockCatServiceInterface_CatSearch_Call) Run(run func(ctx context.Context, params *cat.CatSearchParams)) *MockCatServiceInterface_CatSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatSearchParams
		if args[1] != nil {
			arg1 = args[1].(*cat.CatSearchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_CatSearch_Call) Return(cats []*cat.Cat, err error) *MockCatServiceInterface_CatSearch_Call {
	_c.Call.Return(cats, err)
	return _c
}

func (_c *MockCatServiceInterface_CatSearch_Call) RunAndReturn(run func(ctx context.Context, params *cat.CatSearchParams) ([]*cat.Cat, error)) *MockCatServiceInterface_CatSearch_Call {
	_c.Call.Return(run)
	return _c
}

// ToyByID provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) ToyByID(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID) (*cat.Toy, error) {
	ret := _mock.Called(ctx, catID, toyID)

	if len(ret) == 0 {
		panic("no return value specified for ToyByID")
	}

	var r0 *cat.Toy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.ToyID) (*cat.Toy, error)); ok {
		return returnFunc(ctx, catID, toyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.ToyID) *cat.Toy); ok {
		r0 = returnFunc(ctx, catID, toyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cat.Toy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CatID, *cat.ToyID) error); ok {
		r1 = returnFunc(ctx, catID, toyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_ToyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToyByID'
type MockCatServiceInterface_ToyByID_Call struct {
	*mock.Call
}

// ToyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *cat.CatID
//   - toyID *cat.ToyID
func (_e *MockCatServiceInterface_Expecter) ToyByID(ctx interface{}, catID interface{}, toyID interface{}) *MockCatServiceInterface_ToyByID_Call {
	return &MockCatServiceInterface_ToyByID_Call{Call: _e.mock.On("ToyByID", ctx, catID, toyID)}
}

func (_c *MockCatServiceInterface_ToyByID_Call) Run(run func(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID)) *MockCatServiceInterface_ToyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		var arg2 *cat.ToyID
		if args[2] != nil {
			arg2 = args[2].(*cat.ToyID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_ToyByID_Call) Return(toy *cat.Toy, err error) *MockCatServiceInterface_ToyByID_Call {
	_c.Call.Return(toy, err)
	return _c
}

func (_c *MockCatServiceInterface_ToyByID_Call) RunAndReturn(run func(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID) (*cat.Toy, error)) *MockCatServiceInterface_ToyByID_Call {
	_c.Call.Return(run)
	return _c
}

// ToyCreate provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) ToyCreate(ctx context.Context, catID *cat.CatID, data *cat.ToyCreate) (*cat.ToyID, error) {
	ret := _mock.Called(ctx, catID, data)

	if len(ret) == 0 {
		panic("no return value specified for ToyCreate")
	}

	var r0 *cat.ToyID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.ToyCreate) (*cat.ToyID, error)); ok {
		return returnFunc(ctx, catID, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.ToyCreate) *cat.ToyID); ok {
		r0 = returnFunc(ctx, catID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cat.ToyID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CatID, *cat.ToyCreate) error); ok {
		r1 = returnFunc(ctx, catID, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_ToyCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToyCreate'
type MockCatServiceInterface_ToyCreate_Call struct {
	*mock.Call
}

// ToyCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *cat.CatID
//   - data *cat.ToyCreate
func (_e *MockCatServiceInterface_Expecter) ToyCreate(ctx interface{}, catID interface{}, data interface{}) *MockCatServiceInterface_ToyCreate_Call {
	return &MockCatServiceInterface_ToyCreate_Call{Call: _e.mock.On("ToyCreate", ctx, catID, data)}
}

func (_c *MockCatServiceInterface_ToyCreate_Call) Run(run func(ctx context.Context, catID *cat.CatID, data *cat.ToyCreate)) *MockCatServiceInterface_ToyCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		var arg2 *cat.ToyCreate
		if args[2] != nil {
			arg2 = args[2].(*cat.ToyCreate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_ToyCreate_Call) Return(toyID *cat.ToyID, err error) *MockCatServiceInterface_ToyCreate_Call {
	_c.Call.Return(toyID, err)
	return _c
}

func (_c *MockCatServiceInterface_ToyCreate_Call) RunAndReturn(run func(ctx context.Context, catID *cat.CatID, data *cat.ToyCreate) (*cat.ToyID, error)) *MockCatServiceInterface_ToyCreate_Call {
	_c.Call.Return(run)
	return _c
}

// ToyDelete provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) ToyDelete(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID) error {
	ret := _mock.Called(ctx, catID, toyID)

	if len(ret) == 0 {
		panic("no return value specified for ToyDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.ToyID) error); ok {
		r0 = returnFunc(ctx, catID, toyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatServiceInterface_ToyDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToyDelete'
type MockCatServiceInterface_ToyDelete_Call struct {
	*mock.Call
}

// ToyDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *cat.CatID
//   - toyID *cat.ToyID
func (_e *MockCatServiceInterface_Expecter) ToyDelete(ctx interface{}, catID interface{}, toyID interface{}) *MockCatServiceInterface_ToyDelete_Call {
	return &MockCatServiceInterface_ToyDelete_Call{Call: _e.mock.On("ToyDelete", ctx, catID, toyID)}
}

func (_c *MockCatServiceInterface_ToyDelete_Call) Run(run func(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID)) *MockCatServiceInterface_ToyDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		var arg2 *cat.ToyID
		if args[2] != nil {
			arg2 = args[2].(*cat.ToyID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_ToyDelete_Call) Return(err error) *MockCatServiceInterface_ToyDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatServiceInterface_ToyDelete_Call) RunAndReturn(run func(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID) error) *MockCatServiceInterface_ToyDelete_Call {
	_c.Call.Return(run)
	return _c
}

// ToySearch provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) ToySearch(ctx context.Context, catID *cat.CatID, params *cat.ToySearchParams) ([]*cat.Toy, error) {
	ret := _mock.Called(ctx, catID, params)

	if len(ret) == 0 {
		panic("no return value specified for ToySearch")
	}

	var r0 []*cat.Toy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.ToySearchParams) ([]*cat.Toy, error)); ok {
		return returnFunc(ctx, catID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.ToySearchParams) []*cat.Toy); ok {
		r0 = returnFunc(ctx, catID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*cat.Toy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CatID, *cat.ToySearchParams) error); ok {
		r1 = returnFunc(ctx, catID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_ToySearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToySearch'
type MockCatServiceInterface_ToySearch_Call struct {
	*mock.Call
}

// ToySearch is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *cat.CatID
//   - params *cat.ToySearchParams
func (_e *MockCatServiceInterface_Expecter) ToySearch(ctx interface{}, catID interface{}, params interface{}) *MockCatServiceInterface_ToySearch_Call {
	return &MockCatServiceInterface_ToySearch_Call{Call: _e.mock.On("ToySearch", ctx, catID, params)}
}

func (_c *MockCatServiceInterface_ToySearch_Call) Run(run func(ctx context.Context, catID *cat.CatID, params *cat.ToySearchParams)) *MockCatServiceInterface_ToySearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		var arg2 *cat.ToySearchParams
		if args[2] != nil {
			arg2 = args[2].(*cat.ToySearchParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_ToySearch_Call) Return(toys []*cat.Toy, err error) *MockCatServiceInterface_ToySearch_Call {
	_c.Call.Return(toys, err)
	return _c
}

func (_c *MockCatServiceInterface_ToySearch_Call) RunAndReturn(run func(ctx context.Context, catID *cat.CatID, params *cat.ToySearchParams) ([]*cat.Toy, error)) *MockCatServiceInterface_ToySearch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHelloServiceInterface creates a new instance of MockHelloServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelloServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelloServiceInterface {
	mock := &MockHelloServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHelloServiceInterface is an autogenerated mock type for the HelloServiceInterface type
type MockHelloServiceInterface struct {
	mock.Mock
}

type MockHelloServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelloServiceInterface) EXPECT() *MockHelloServiceInterface_Expecter {
	return &MockHelloServiceInterface_Expecter{mock: &_m.Mock}
}

// GetHelloMessage provides a mock function for the type MockHelloServiceInterface
func (_mock *MockHelloServiceInterface) GetHelloMessage(context1 context.Context) (*hello.Message, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetHelloMessage")
	}

	var r0 *hello.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*hello.Message, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *hello.Message); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hello.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHelloServiceInterface_GetHelloMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHelloMessage'
type MockHelloServiceInterface_GetHelloMessage_Call struct {
	*mock.Call
}

// GetHelloMessage is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHelloServiceInterface_Expecter) GetHelloMessage(context1 interface{}) *MockHelloServiceInterface_GetHelloMessage_Call {
	return &MockHelloServiceInterface_GetHelloMessage_Call{Call: _e.mock.On("GetHelloMessage", context1)}
}

func (_c *MockHelloServiceInterface_GetHelloMessage_Call) Run(run func(context1 context.Context)) *MockHelloServiceInterface_GetHelloMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHelloServiceInterface_GetHelloMessage_Call) Return(message *hello.Message, err error) *MockHelloServiceInterface_GetHelloMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockHelloServiceInterface_GetHelloMessage_Call) RunAndReturn(run func(context1 context.Context) (*hello.Message, error)) *MockHelloServiceInterface_GetHelloMessage_Call {
	_c.Call.Return(run)
	return _c
}
