// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"context"

	"github.com/Irurnnen/go-gin-template/internal/services/hello"
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHelloHandlerInterface creates a new instance of MockHelloHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelloHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelloHandlerInterface {
	mock := &MockHelloHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHelloHandlerInterface is an autogenerated mock type for the HelloHandlerInterface type
type MockHelloHandlerInterface struct {
	mock.Mock
}

type MockHelloHandlerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelloHandlerInterface) EXPECT() *MockHelloHandlerInterface_Expecter {
	return &MockHelloHandlerInterface_Expecter{mock: &_m.Mock}
}

// GetHelloMessage provides a mock function for the type MockHelloHandlerInterface
func (_mock *MockHelloHandlerInterface) GetHelloMessage(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockHelloHandlerInterface_GetHelloMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHelloMessage'
type MockHelloHandlerInterface_GetHelloMessage_Call struct {
	*mock.Call
}

// GetHelloMessage is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockHelloHandlerInterface_Expecter) GetHelloMessage(c interface{}) *MockHelloHandlerInterface_GetHelloMessage_Call {
	return &MockHelloHandlerInterface_GetHelloMessage_Call{Call: _e.mock.On("GetHelloMessage", c)}
}

func (_c *MockHelloHandlerInterface_GetHelloMessage_Call) Run(run func(c *gin.Context)) *MockHelloHandlerInterface_GetHelloMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHelloHandlerInterface_GetHelloMessage_Call) Return() *MockHelloHandlerInterface_GetHelloMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHelloHandlerInterface_GetHelloMessage_Call) RunAndReturn(run func(c *gin.Context)) *MockHelloHandlerInterface_GetHelloMessage_Call {
	_c.Run(run)
	return _c
}

// NewMockHelloServiceInterface creates a new instance of MockHelloServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelloServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelloServiceInterface {
	mock := &MockHelloServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHelloServiceInterface is an autogenerated mock type for the HelloServiceInterface type
type MockHelloServiceInterface struct {
	mock.Mock
}

type MockHelloServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelloServiceInterface) EXPECT() *MockHelloServiceInterface_Expecter {
	return &MockHelloServiceInterface_Expecter{mock: &_m.Mock}
}

// GetHelloMessage provides a mock function for the type MockHelloServiceInterface
func (_mock *MockHelloServiceInterface) GetHelloMessage(context1 context.Context) (*hello.Message, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetHelloMessage")
	}

	var r0 *hello.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*hello.Message, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *hello.Message); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hello.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHelloServiceInterface_GetHelloMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHelloMessage'
type MockHelloServiceInterface_GetHelloMessage_Call struct {
	*mock.Call
}

// GetHelloMessage is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHelloServiceInterface_Expecter) GetHelloMessage(context1 interface{}) *MockHelloServiceInterface_GetHelloMessage_Call {
	return &MockHelloServiceInterface_GetHelloMessage_Call{Call: _e.mock.On("GetHelloMessage", context1)}
}

func (_c *MockHelloServiceInterface_GetHelloMessage_Call) Run(run func(context1 context.Context)) *MockHelloServiceInterface_GetHelloMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHelloServiceInterface_GetHelloMessage_Call) Return(message *hello.Message, err error) *MockHelloServiceInterface_GetHelloMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockHelloServiceInterface_GetHelloMessage_Call) RunAndReturn(run func(context1 context.Context) (*hello.Message, error)) *MockHelloServiceInterface_GetHelloMessage_Call {
	_c.Call.Return(run)
	return _c
}
