// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"context"

	"github.com/Irurnnen/go-gin-template/internal/services/cat"
	"github.com/Irurnnen/go-gin-template/internal/services/hello"
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCatHandlerInterface creates a new instance of MockCatHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatHandlerInterface {
	mock := &MockCatHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatHandlerInterface is an autogenerated mock type for the CatHandlerInterface type
type MockCatHandlerInterface struct {
	mock.Mock
}

type MockCatHandlerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatHandlerInterface) EXPECT() *MockCatHandlerInterface_Expecter {
	return &MockCatHandlerInterface_Expecter{mock: &_m.Mock}
}

// AddToy provides a mock function for the type MockCatHandlerInterface
func (_mock *MockCatHandlerInterface) AddToy(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockCatHandlerInterface_AddToy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToy'
type MockCatHandlerInterface_AddToy_Call struct {
	*mock.Call
}

// AddToy is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockCatHandlerInterface_Expecter) AddToy(ctx interface{}) *MockCatHandlerInterface_AddToy_Call {
	return &MockCatHandlerInterface_AddToy_Call{Call: _e.mock.On("AddToy", ctx)}
}

func (_c *MockCatHandlerInterface_AddToy_Call) Run(run func(ctx *gin.Context)) *MockCatHandlerInterface_AddToy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatHandlerInterface_AddToy_Call) Return() *MockCatHandlerInterface_AddToy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCatHandlerInterface_AddToy_Call) RunAndReturn(run func(ctx *gin.Context)) *MockCatHandlerInterface_AddToy_Call {
	_c.Run(run)
	return _c
}

// ChangeStatus provides a mock function for the type MockCatHandlerInterface
func (_mock *MockCatHandlerInterface) ChangeStatus(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockCatHandlerInterface_ChangeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeStatus'
type MockCatHandlerInterface_ChangeStatus_Call struct {
	*mock.Call
}

// ChangeStatus is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockCatHandlerInterface_Expecter) ChangeStatus(ctx interface{}) *MockCatHandlerInterface_ChangeStatus_Call {
	return &MockCatHandlerInterface_ChangeStatus_Call{Call: _e.mock.On("ChangeStatus", ctx)}
}

func (_c *MockCatHandlerInterface_ChangeStatus_Call) Run(run func(ctx *gin.Context)) *MockCatHandlerInterface_ChangeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatHandlerInterface_ChangeStatus_Call) Return() *MockCatHandlerInterface_ChangeStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCatHandlerInterface_ChangeStatus_Call) RunAndReturn(run func(ctx *gin.Context)) *MockCatHandlerInterface_ChangeStatus_Call {
	_c.Run(run)
	return _c
}

// Create provides a mock function for the type MockCatHandlerInterface
func (_mock *MockCatHandlerInterface) Create(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockCatHandlerInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCatHandlerInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockCatHandlerInterface_Expecter) Create(ctx interface{}) *MockCatHandlerInterface_Create_Call {
	return &MockCatHandlerInterface_Create_Call{Call: _e.mock.On("Create", ctx)}
}

func (_c *MockCatHandlerInterface_Create_Call) Run(run func(ctx *gin.Context)) *MockCatHandlerInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatHandlerInterface_Create_Call) Return() *MockCatHandlerInterface_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCatHandlerInterface_Create_Call) RunAndReturn(run func(ctx *gin.Context)) *MockCatHandlerInterface_Create_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type MockCatHandlerInterface
func (_mock *MockCatHandlerInterface) Delete(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockCatHandlerInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCatHandlerInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockCatHandlerInterface_Expecter) Delete(ctx interface{}) *MockCatHandlerInterface_Delete_Call {
	return &MockCatHandlerInterface_Delete_Call{Call: _e.mock.On("Delete", ctx)}
}

func (_c *MockCatHandlerInterface_Delete_Call) Run(run func(ctx *gin.Context)) *MockCatHandlerInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatHandlerInterface_Delete_Call) Return() *MockCatHandlerInterface_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCatHandlerInterface_Delete_Call) RunAndReturn(run func(ctx *gin.Context)) *MockCatHandlerInterface_Delete_Call {
	_c.Run(run)
	return _c
}

// DeleteToy provides a mock function for the type MockCatHandlerInterface
func (_mock *MockCatHandlerInterface) DeleteToy(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockCatHandlerInterface_DeleteToy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteToy'
type MockCatHandlerInterface_DeleteToy_Call struct {
	*mock.Call
}

// DeleteToy is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockCatHandlerInterface_Expecter) DeleteToy(ctx interface{}) *MockCatHandlerInterface_DeleteToy_Call {
	return &MockCatHandlerInterface_DeleteToy_Call{Call: _e.mock.On("DeleteToy", ctx)}
}

func (_c *MockCatHandlerInterface_DeleteToy_Call) Run(run func(ctx *gin.Context)) *MockCatHandlerInterface_DeleteToy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatHandlerInterface_DeleteToy_Call) Return() *MockCatHandlerInterface_DeleteToy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCatHandlerInterface_DeleteToy_Call) RunAndReturn(run func(ctx *gin.Context)) *MockCatHandlerInterface_DeleteToy_Call {
	_c.Run(run)
	return _c
}

// GetByID provides a mock function for the type MockCatHandlerInterface
func (_mock *MockCatHandlerInterface) GetByID(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockCatHandlerInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCatHandlerInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockCatHandlerInterface_Expecter) GetByID(ctx interface{}) *MockCatHandlerInterface_GetByID_Call {
	return &MockCatHandlerInterface_GetByID_Call{Call: _e.mock.On("GetByID", ctx)}
}

func (_c *MockCatHandlerInterface_GetByID_Call) Run(run func(ctx *gin.Context)) *MockCatHandlerInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatHandlerInterface_GetByID_Call) Return() *MockCatHandlerInterface_GetByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCatHandlerInterface_GetByID_Call) RunAndReturn(run func(ctx *gin.Context)) *MockCatHandlerInterface_GetByID_Call {
	_c.Run(run)
	return _c
}

// GetToyByID provides a mock function for the type MockCatHandlerInterface
func (_mock *MockCatHandlerInterface) GetToyByID(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockCatHandlerInterface_GetToyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToyByID'
type MockCatHandlerInterface_GetToyByID_Call struct {
	*mock.Call
}

// GetToyByID is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockCatHandlerInterface_Expecter) GetToyByID(ctx interface{}) *MockCatHandlerInterface_GetToyByID_Call {
	return &MockCatHandlerInterface_GetToyByID_Call{Call: _e.mock.On("GetToyByID", ctx)}
}

func (_c *MockCatHandlerInterface_GetToyByID_Call) Run(run func(ctx *gin.Context)) *MockCatHandlerInterface_GetToyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatHandlerInterface_GetToyByID_Call) Return() *MockCatHandlerInterface_GetToyByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCatHandlerInterface_GetToyByID_Call) RunAndReturn(run func(ctx *gin.Context)) *MockCatHandlerInterface_GetToyByID_Call {
	_c.Run(run)
	return _c
}

// GetToys provides a mock function for the type MockCatHandlerInterface
func (_mock *MockCatHandlerInterface) GetToys(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockCatHandlerInterface_GetToys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToys'
type MockCatHandlerInterface_GetToys_Call struct {
	*mock.Call
}

// GetToys is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockCatHandlerInterface_Expecter) GetToys(ctx interface{}) *MockCatHandlerInterface_GetToys_Call {
	return &MockCatHandlerInterface_GetToys_Call{Call: _e.mock.On("GetToys", ctx)}
}

func (_c *MockCatHandlerInterface_GetToys_Call) Run(run func(ctx *gin.Context)) *MockCatHandlerInterface_GetToys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatHandlerInterface_GetToys_Call) Return() *MockCatHandlerInterface_GetToys_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCatHandlerInterface_GetToys_Call) RunAndReturn(run func(ctx *gin.Context)) *MockCatHandlerInterface_GetToys_Call {
	_c.Run(run)
	return _c
}

// Search provides a mock function for the type MockCatHandlerInterface
func (_mock *MockCatHandlerInterface) Search(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockCatHandlerInterface_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockCatHandlerInterface_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockCatHandlerInterface_Expecter) Search(ctx interface{}) *MockCatHandlerInterface_Search_Call {
	return &MockCatHandlerInterface_Search_Call{Call: _e.mock.On("Search", ctx)}
}

func (_c *MockCatHandlerInterface_Search_Call) Run(run func(ctx *gin.Context)) *MockCatHandlerInterface_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatHandlerInterface_Search_Call) Return() *MockCatHandlerInterface_Search_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCatHandlerInterface_Search_Call) RunAndReturn(run func(ctx *gin.Context)) *MockCatHandlerInterface_Search_Call {
	_c.Run(run)
	return _c
}

// NewMockCatServiceInterface creates a new instance of MockCatServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatServiceInterface {
	mock := &MockCatServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatServiceInterface is an autogenerated mock type for the CatServiceInterface type
type MockCatServiceInterface struct {
	mock.Mock
}

type MockCatServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatServiceInterface) EXPECT() *MockCatServiceInterface_Expecter {
	return &MockCatServiceInterface_Expecter{mock: &_m.Mock}
}

// AddToy provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) AddToy(ctx context.Context, catID *cat.CatID, data *cat.CreateToy) (*cat.ToyID, error) {
	ret := _mock.Called(ctx, catID, data)

	if len(ret) == 0 {
		panic("no return value specified for AddToy")
	}

	var r0 *cat.ToyID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.CreateToy) (*cat.ToyID, error)); ok {
		return returnFunc(ctx, catID, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.CreateToy) *cat.ToyID); ok {
		r0 = returnFunc(ctx, catID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cat.ToyID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CatID, *cat.CreateToy) error); ok {
		r1 = returnFunc(ctx, catID, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_AddToy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToy'
type MockCatServiceInterface_AddToy_Call struct {
	*mock.Call
}

// AddToy is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *cat.CatID
//   - data *cat.CreateToy
func (_e *MockCatServiceInterface_Expecter) AddToy(ctx interface{}, catID interface{}, data interface{}) *MockCatServiceInterface_AddToy_Call {
	return &MockCatServiceInterface_AddToy_Call{Call: _e.mock.On("AddToy", ctx, catID, data)}
}

func (_c *MockCatServiceInterface_AddToy_Call) Run(run func(ctx context.Context, catID *cat.CatID, data *cat.CreateToy)) *MockCatServiceInterface_AddToy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		var arg2 *cat.CreateToy
		if args[2] != nil {
			arg2 = args[2].(*cat.CreateToy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_AddToy_Call) Return(toyID *cat.ToyID, err error) *MockCatServiceInterface_AddToy_Call {
	_c.Call.Return(toyID, err)
	return _c
}

func (_c *MockCatServiceInterface_AddToy_Call) RunAndReturn(run func(ctx context.Context, catID *cat.CatID, data *cat.CreateToy) (*cat.ToyID, error)) *MockCatServiceInterface_AddToy_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeStatus provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) ChangeStatus(ctx context.Context, id *cat.CatID, status *cat.CatStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for ChangeStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.CatStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatServiceInterface_ChangeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeStatus'
type MockCatServiceInterface_ChangeStatus_Call struct {
	*mock.Call
}

// ChangeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id *cat.CatID
//   - status *cat.CatStatus
func (_e *MockCatServiceInterface_Expecter) ChangeStatus(ctx interface{}, id interface{}, status interface{}) *MockCatServiceInterface_ChangeStatus_Call {
	return &MockCatServiceInterface_ChangeStatus_Call{Call: _e.mock.On("ChangeStatus", ctx, id, status)}
}

func (_c *MockCatServiceInterface_ChangeStatus_Call) Run(run func(ctx context.Context, id *cat.CatID, status *cat.CatStatus)) *MockCatServiceInterface_ChangeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		var arg2 *cat.CatStatus
		if args[2] != nil {
			arg2 = args[2].(*cat.CatStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_ChangeStatus_Call) Return(err error) *MockCatServiceInterface_ChangeStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatServiceInterface_ChangeStatus_Call) RunAndReturn(run func(ctx context.Context, id *cat.CatID, status *cat.CatStatus) error) *MockCatServiceInterface_ChangeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) Create(ctx context.Context, data *cat.CreateCat) (*cat.CatID, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *cat.CatID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CreateCat) (*cat.CatID, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CreateCat) *cat.CatID); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cat.CatID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CreateCat) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCatServiceInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data *cat.CreateCat
func (_e *MockCatServiceInterface_Expecter) Create(ctx interface{}, data interface{}) *MockCatServiceInterface_Create_Call {
	return &MockCatServiceInterface_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockCatServiceInterface_Create_Call) Run(run func(ctx context.Context, data *cat.CreateCat)) *MockCatServiceInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CreateCat
		if args[1] != nil {
			arg1 = args[1].(*cat.CreateCat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_Create_Call) Return(catID *cat.CatID, err error) *MockCatServiceInterface_Create_Call {
	_c.Call.Return(catID, err)
	return _c
}

func (_c *MockCatServiceInterface_Create_Call) RunAndReturn(run func(ctx context.Context, data *cat.CreateCat) (*cat.CatID, error)) *MockCatServiceInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) Delete(ctx context.Context, id *cat.CatID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatServiceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCatServiceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id *cat.CatID
func (_e *MockCatServiceInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockCatServiceInterface_Delete_Call {
	return &MockCatServiceInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCatServiceInterface_Delete_Call) Run(run func(ctx context.Context, id *cat.CatID)) *MockCatServiceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_Delete_Call) Return(err error) *MockCatServiceInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatServiceInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, id *cat.CatID) error) *MockCatServiceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteToy provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) DeleteToy(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID) error {
	ret := _mock.Called(ctx, catID, toyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteToy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.ToyID) error); ok {
		r0 = returnFunc(ctx, catID, toyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatServiceInterface_DeleteToy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteToy'
type MockCatServiceInterface_DeleteToy_Call struct {
	*mock.Call
}

// DeleteToy is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *cat.CatID
//   - toyID *cat.ToyID
func (_e *MockCatServiceInterface_Expecter) DeleteToy(ctx interface{}, catID interface{}, toyID interface{}) *MockCatServiceInterface_DeleteToy_Call {
	return &MockCatServiceInterface_DeleteToy_Call{Call: _e.mock.On("DeleteToy", ctx, catID, toyID)}
}

func (_c *MockCatServiceInterface_DeleteToy_Call) Run(run func(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID)) *MockCatServiceInterface_DeleteToy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		var arg2 *cat.ToyID
		if args[2] != nil {
			arg2 = args[2].(*cat.ToyID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_DeleteToy_Call) Return(err error) *MockCatServiceInterface_DeleteToy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatServiceInterface_DeleteToy_Call) RunAndReturn(run func(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID) error) *MockCatServiceInterface_DeleteToy_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) GetByID(ctx context.Context, id *cat.CatID) (*cat.Cat, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *cat.Cat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID) (*cat.Cat, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID) *cat.Cat); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cat.Cat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CatID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCatServiceInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id *cat.CatID
func (_e *MockCatServiceInterface_Expecter) GetByID(ctx interface{}, id interface{}) *MockCatServiceInterface_GetByID_Call {
	return &MockCatServiceInterface_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCatServiceInterface_GetByID_Call) Run(run func(ctx context.Context, id *cat.CatID)) *MockCatServiceInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_GetByID_Call) Return(cat1 *cat.Cat, err error) *MockCatServiceInterface_GetByID_Call {
	_c.Call.Return(cat1, err)
	return _c
}

func (_c *MockCatServiceInterface_GetByID_Call) RunAndReturn(run func(ctx context.Context, id *cat.CatID) (*cat.Cat, error)) *MockCatServiceInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetToyByID provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) GetToyByID(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID) (*cat.Toy, error) {
	ret := _mock.Called(ctx, catID, toyID)

	if len(ret) == 0 {
		panic("no return value specified for GetToyByID")
	}

	var r0 *cat.Toy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.ToyID) (*cat.Toy, error)); ok {
		return returnFunc(ctx, catID, toyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID, *cat.ToyID) *cat.Toy); ok {
		r0 = returnFunc(ctx, catID, toyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cat.Toy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CatID, *cat.ToyID) error); ok {
		r1 = returnFunc(ctx, catID, toyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_GetToyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToyByID'
type MockCatServiceInterface_GetToyByID_Call struct {
	*mock.Call
}

// GetToyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *cat.CatID
//   - toyID *cat.ToyID
func (_e *MockCatServiceInterface_Expecter) GetToyByID(ctx interface{}, catID interface{}, toyID interface{}) *MockCatServiceInterface_GetToyByID_Call {
	return &MockCatServiceInterface_GetToyByID_Call{Call: _e.mock.On("GetToyByID", ctx, catID, toyID)}
}

func (_c *MockCatServiceInterface_GetToyByID_Call) Run(run func(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID)) *MockCatServiceInterface_GetToyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		var arg2 *cat.ToyID
		if args[2] != nil {
			arg2 = args[2].(*cat.ToyID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_GetToyByID_Call) Return(toy *cat.Toy, err error) *MockCatServiceInterface_GetToyByID_Call {
	_c.Call.Return(toy, err)
	return _c
}

func (_c *MockCatServiceInterface_GetToyByID_Call) RunAndReturn(run func(ctx context.Context, catID *cat.CatID, toyID *cat.ToyID) (*cat.Toy, error)) *MockCatServiceInterface_GetToyByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetToys provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) GetToys(ctx context.Context, catID *cat.CatID) ([]*cat.Toy, error) {
	ret := _mock.Called(ctx, catID)

	if len(ret) == 0 {
		panic("no return value specified for GetToys")
	}

	var r0 []*cat.Toy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID) ([]*cat.Toy, error)); ok {
		return returnFunc(ctx, catID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatID) []*cat.Toy); ok {
		r0 = returnFunc(ctx, catID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*cat.Toy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CatID) error); ok {
		r1 = returnFunc(ctx, catID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_GetToys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToys'
type MockCatServiceInterface_GetToys_Call struct {
	*mock.Call
}

// GetToys is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *cat.CatID
func (_e *MockCatServiceInterface_Expecter) GetToys(ctx interface{}, catID interface{}) *MockCatServiceInterface_GetToys_Call {
	return &MockCatServiceInterface_GetToys_Call{Call: _e.mock.On("GetToys", ctx, catID)}
}

func (_c *MockCatServiceInterface_GetToys_Call) Run(run func(ctx context.Context, catID *cat.CatID)) *MockCatServiceInterface_GetToys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatID
		if args[1] != nil {
			arg1 = args[1].(*cat.CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_GetToys_Call) Return(toys []*cat.Toy, err error) *MockCatServiceInterface_GetToys_Call {
	_c.Call.Return(toys, err)
	return _c
}

func (_c *MockCatServiceInterface_GetToys_Call) RunAndReturn(run func(ctx context.Context, catID *cat.CatID) ([]*cat.Toy, error)) *MockCatServiceInterface_GetToys_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockCatServiceInterface
func (_mock *MockCatServiceInterface) Search(ctx context.Context, params *cat.CatSearchParams) ([]*cat.Cat, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*cat.Cat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatSearchParams) ([]*cat.Cat, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cat.CatSearchParams) []*cat.Cat); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*cat.Cat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cat.CatSearchParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatServiceInterface_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockCatServiceInterface_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - params *cat.CatSearchParams
func (_e *MockCatServiceInterface_Expecter) Search(ctx interface{}, params interface{}) *MockCatServiceInterface_Search_Call {
	return &MockCatServiceInterface_Search_Call{Call: _e.mock.On("Search", ctx, params)}
}

func (_c *MockCatServiceInterface_Search_Call) Run(run func(ctx context.Context, params *cat.CatSearchParams)) *MockCatServiceInterface_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cat.CatSearchParams
		if args[1] != nil {
			arg1 = args[1].(*cat.CatSearchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatServiceInterface_Search_Call) Return(cats []*cat.Cat, err error) *MockCatServiceInterface_Search_Call {
	_c.Call.Return(cats, err)
	return _c
}

func (_c *MockCatServiceInterface_Search_Call) RunAndReturn(run func(ctx context.Context, params *cat.CatSearchParams) ([]*cat.Cat, error)) *MockCatServiceInterface_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHelloHandlerInterface creates a new instance of MockHelloHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelloHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelloHandlerInterface {
	mock := &MockHelloHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHelloHandlerInterface is an autogenerated mock type for the HelloHandlerInterface type
type MockHelloHandlerInterface struct {
	mock.Mock
}

type MockHelloHandlerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelloHandlerInterface) EXPECT() *MockHelloHandlerInterface_Expecter {
	return &MockHelloHandlerInterface_Expecter{mock: &_m.Mock}
}

// GetHelloMessage provides a mock function for the type MockHelloHandlerInterface
func (_mock *MockHelloHandlerInterface) GetHelloMessage(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockHelloHandlerInterface_GetHelloMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHelloMessage'
type MockHelloHandlerInterface_GetHelloMessage_Call struct {
	*mock.Call
}

// GetHelloMessage is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockHelloHandlerInterface_Expecter) GetHelloMessage(c interface{}) *MockHelloHandlerInterface_GetHelloMessage_Call {
	return &MockHelloHandlerInterface_GetHelloMessage_Call{Call: _e.mock.On("GetHelloMessage", c)}
}

func (_c *MockHelloHandlerInterface_GetHelloMessage_Call) Run(run func(c *gin.Context)) *MockHelloHandlerInterface_GetHelloMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHelloHandlerInterface_GetHelloMessage_Call) Return() *MockHelloHandlerInterface_GetHelloMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHelloHandlerInterface_GetHelloMessage_Call) RunAndReturn(run func(c *gin.Context)) *MockHelloHandlerInterface_GetHelloMessage_Call {
	_c.Run(run)
	return _c
}

// NewMockHelloServiceInterface creates a new instance of MockHelloServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelloServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelloServiceInterface {
	mock := &MockHelloServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHelloServiceInterface is an autogenerated mock type for the HelloServiceInterface type
type MockHelloServiceInterface struct {
	mock.Mock
}

type MockHelloServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelloServiceInterface) EXPECT() *MockHelloServiceInterface_Expecter {
	return &MockHelloServiceInterface_Expecter{mock: &_m.Mock}
}

// GetHelloMessage provides a mock function for the type MockHelloServiceInterface
func (_mock *MockHelloServiceInterface) GetHelloMessage(context1 context.Context) (*hello.Message, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetHelloMessage")
	}

	var r0 *hello.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*hello.Message, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *hello.Message); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hello.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHelloServiceInterface_GetHelloMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHelloMessage'
type MockHelloServiceInterface_GetHelloMessage_Call struct {
	*mock.Call
}

// GetHelloMessage is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHelloServiceInterface_Expecter) GetHelloMessage(context1 interface{}) *MockHelloServiceInterface_GetHelloMessage_Call {
	return &MockHelloServiceInterface_GetHelloMessage_Call{Call: _e.mock.On("GetHelloMessage", context1)}
}

func (_c *MockHelloServiceInterface_GetHelloMessage_Call) Run(run func(context1 context.Context)) *MockHelloServiceInterface_GetHelloMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHelloServiceInterface_GetHelloMessage_Call) Return(message *hello.Message, err error) *MockHelloServiceInterface_GetHelloMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockHelloServiceInterface_GetHelloMessage_Call) RunAndReturn(run func(context1 context.Context) (*hello.Message, error)) *MockHelloServiceInterface_GetHelloMessage_Call {
	_c.Call.Return(run)
	return _c
}
