// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cat

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCatRepositoryInterface creates a new instance of MockCatRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatRepositoryInterface {
	mock := &MockCatRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatRepositoryInterface is an autogenerated mock type for the CatRepositoryInterface type
type MockCatRepositoryInterface struct {
	mock.Mock
}

type MockCatRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatRepositoryInterface) EXPECT() *MockCatRepositoryInterface_Expecter {
	return &MockCatRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CatByID provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) CatByID(ctx context.Context, id *CatID) (*Cat, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CatByID")
	}

	var r0 *Cat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID) (*Cat, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID) *Cat); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Cat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *CatID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatRepositoryInterface_CatByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatByID'
type MockCatRepositoryInterface_CatByID_Call struct {
	*mock.Call
}

// CatByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id *CatID
func (_e *MockCatRepositoryInterface_Expecter) CatByID(ctx interface{}, id interface{}) *MockCatRepositoryInterface_CatByID_Call {
	return &MockCatRepositoryInterface_CatByID_Call{Call: _e.mock.On("CatByID", ctx, id)}
}

func (_c *MockCatRepositoryInterface_CatByID_Call) Run(run func(ctx context.Context, id *CatID)) *MockCatRepositoryInterface_CatByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_CatByID_Call) Return(cat *Cat, err error) *MockCatRepositoryInterface_CatByID_Call {
	_c.Call.Return(cat, err)
	return _c
}

func (_c *MockCatRepositoryInterface_CatByID_Call) RunAndReturn(run func(ctx context.Context, id *CatID) (*Cat, error)) *MockCatRepositoryInterface_CatByID_Call {
	_c.Call.Return(run)
	return _c
}

// CatChangeStatus provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) CatChangeStatus(ctx context.Context, id *CatID, status *CatStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for CatChangeStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID, *CatStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_CatChangeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatChangeStatus'
type MockCatRepositoryInterface_CatChangeStatus_Call struct {
	*mock.Call
}

// CatChangeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id *CatID
//   - status *CatStatus
func (_e *MockCatRepositoryInterface_Expecter) CatChangeStatus(ctx interface{}, id interface{}, status interface{}) *MockCatRepositoryInterface_CatChangeStatus_Call {
	return &MockCatRepositoryInterface_CatChangeStatus_Call{Call: _e.mock.On("CatChangeStatus", ctx, id, status)}
}

func (_c *MockCatRepositoryInterface_CatChangeStatus_Call) Run(run func(ctx context.Context, id *CatID, status *CatStatus)) *MockCatRepositoryInterface_CatChangeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		var arg2 *CatStatus
		if args[2] != nil {
			arg2 = args[2].(*CatStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_CatChangeStatus_Call) Return(err error) *MockCatRepositoryInterface_CatChangeStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_CatChangeStatus_Call) RunAndReturn(run func(ctx context.Context, id *CatID, status *CatStatus) error) *MockCatRepositoryInterface_CatChangeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CatCreate provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) CatCreate(ctx context.Context, data *CatCreateRepo) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CatCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatCreateRepo) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_CatCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatCreate'
type MockCatRepositoryInterface_CatCreate_Call struct {
	*mock.Call
}

// CatCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - data *CatCreateRepo
func (_e *MockCatRepositoryInterface_Expecter) CatCreate(ctx interface{}, data interface{}) *MockCatRepositoryInterface_CatCreate_Call {
	return &MockCatRepositoryInterface_CatCreate_Call{Call: _e.mock.On("CatCreate", ctx, data)}
}

func (_c *MockCatRepositoryInterface_CatCreate_Call) Run(run func(ctx context.Context, data *CatCreateRepo)) *MockCatRepositoryInterface_CatCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatCreateRepo
		if args[1] != nil {
			arg1 = args[1].(*CatCreateRepo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_CatCreate_Call) Return(err error) *MockCatRepositoryInterface_CatCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_CatCreate_Call) RunAndReturn(run func(ctx context.Context, data *CatCreateRepo) error) *MockCatRepositoryInterface_CatCreate_Call {
	_c.Call.Return(run)
	return _c
}

// CatDelete provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) CatDelete(ctx context.Context, id *CatID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CatDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_CatDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatDelete'
type MockCatRepositoryInterface_CatDelete_Call struct {
	*mock.Call
}

// CatDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id *CatID
func (_e *MockCatRepositoryInterface_Expecter) CatDelete(ctx interface{}, id interface{}) *MockCatRepositoryInterface_CatDelete_Call {
	return &MockCatRepositoryInterface_CatDelete_Call{Call: _e.mock.On("CatDelete", ctx, id)}
}

func (_c *MockCatRepositoryInterface_CatDelete_Call) Run(run func(ctx context.Context, id *CatID)) *MockCatRepositoryInterface_CatDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_CatDelete_Call) Return(err error) *MockCatRepositoryInterface_CatDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_CatDelete_Call) RunAndReturn(run func(ctx context.Context, id *CatID) error) *MockCatRepositoryInterface_CatDelete_Call {
	_c.Call.Return(run)
	return _c
}

// CatExists provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) CatExists(ctx context.Context, id *CatID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CatExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_CatExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatExists'
type MockCatRepositoryInterface_CatExists_Call struct {
	*mock.Call
}

// CatExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id *CatID
func (_e *MockCatRepositoryInterface_Expecter) CatExists(ctx interface{}, id interface{}) *MockCatRepositoryInterface_CatExists_Call {
	return &MockCatRepositoryInterface_CatExists_Call{Call: _e.mock.On("CatExists", ctx, id)}
}

func (_c *MockCatRepositoryInterface_CatExists_Call) Run(run func(ctx context.Context, id *CatID)) *MockCatRepositoryInterface_CatExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_CatExists_Call) Return(err error) *MockCatRepositoryInterface_CatExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_CatExists_Call) RunAndReturn(run func(ctx context.Context, id *CatID) error) *MockCatRepositoryInterface_CatExists_Call {
	_c.Call.Return(run)
	return _c
}

// CatSearch provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) CatSearch(ctx context.Context, params *CatSearchParams) ([]*Cat, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CatSearch")
	}

	var r0 []*Cat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatSearchParams) ([]*Cat, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatSearchParams) []*Cat); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Cat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *CatSearchParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatRepositoryInterface_CatSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatSearch'
type MockCatRepositoryInterface_CatSearch_Call struct {
	*mock.Call
}

// CatSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - params *CatSearchParams
func (_e *MockCatRepositoryInterface_Expecter) CatSearch(ctx interface{}, params interface{}) *MockCatRepositoryInterface_CatSearch_Call {
	return &MockCatRepositoryInterface_CatSearch_Call{Call: _e.mock.On("CatSearch", ctx, params)}
}

func (_c *MockCatRepositoryInterface_CatSearch_Call) Run(run func(ctx context.Context, params *CatSearchParams)) *MockCatRepositoryInterface_CatSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatSearchParams
		if args[1] != nil {
			arg1 = args[1].(*CatSearchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_CatSearch_Call) Return(cats []*Cat, err error) *MockCatRepositoryInterface_CatSearch_Call {
	_c.Call.Return(cats, err)
	return _c
}

func (_c *MockCatRepositoryInterface_CatSearch_Call) RunAndReturn(run func(ctx context.Context, params *CatSearchParams) ([]*Cat, error)) *MockCatRepositoryInterface_CatSearch_Call {
	_c.Call.Return(run)
	return _c
}

// ToyBelongs provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) ToyBelongs(ctx context.Context, catID *CatID, toyID *ToyID) error {
	ret := _mock.Called(ctx, catID, toyID)

	if len(ret) == 0 {
		panic("no return value specified for ToyBelongs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID, *ToyID) error); ok {
		r0 = returnFunc(ctx, catID, toyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_ToyBelongs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToyBelongs'
type MockCatRepositoryInterface_ToyBelongs_Call struct {
	*mock.Call
}

// ToyBelongs is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *CatID
//   - toyID *ToyID
func (_e *MockCatRepositoryInterface_Expecter) ToyBelongs(ctx interface{}, catID interface{}, toyID interface{}) *MockCatRepositoryInterface_ToyBelongs_Call {
	return &MockCatRepositoryInterface_ToyBelongs_Call{Call: _e.mock.On("ToyBelongs", ctx, catID, toyID)}
}

func (_c *MockCatRepositoryInterface_ToyBelongs_Call) Run(run func(ctx context.Context, catID *CatID, toyID *ToyID)) *MockCatRepositoryInterface_ToyBelongs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		var arg2 *ToyID
		if args[2] != nil {
			arg2 = args[2].(*ToyID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_ToyBelongs_Call) Return(err error) *MockCatRepositoryInterface_ToyBelongs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_ToyBelongs_Call) RunAndReturn(run func(ctx context.Context, catID *CatID, toyID *ToyID) error) *MockCatRepositoryInterface_ToyBelongs_Call {
	_c.Call.Return(run)
	return _c
}

// ToyByID provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) ToyByID(ctx context.Context, toyID *ToyID) (*Toy, error) {
	ret := _mock.Called(ctx, toyID)

	if len(ret) == 0 {
		panic("no return value specified for ToyByID")
	}

	var r0 *Toy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ToyID) (*Toy, error)); ok {
		return returnFunc(ctx, toyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ToyID) *Toy); ok {
		r0 = returnFunc(ctx, toyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Toy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ToyID) error); ok {
		r1 = returnFunc(ctx, toyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatRepositoryInterface_ToyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToyByID'
type MockCatRepositoryInterface_ToyByID_Call struct {
	*mock.Call
}

// ToyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - toyID *ToyID
func (_e *MockCatRepositoryInterface_Expecter) ToyByID(ctx interface{}, toyID interface{}) *MockCatRepositoryInterface_ToyByID_Call {
	return &MockCatRepositoryInterface_ToyByID_Call{Call: _e.mock.On("ToyByID", ctx, toyID)}
}

func (_c *MockCatRepositoryInterface_ToyByID_Call) Run(run func(ctx context.Context, toyID *ToyID)) *MockCatRepositoryInterface_ToyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ToyID
		if args[1] != nil {
			arg1 = args[1].(*ToyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_ToyByID_Call) Return(toy *Toy, err error) *MockCatRepositoryInterface_ToyByID_Call {
	_c.Call.Return(toy, err)
	return _c
}

func (_c *MockCatRepositoryInterface_ToyByID_Call) RunAndReturn(run func(ctx context.Context, toyID *ToyID) (*Toy, error)) *MockCatRepositoryInterface_ToyByID_Call {
	_c.Call.Return(run)
	return _c
}

// ToyCreate provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) ToyCreate(ctx context.Context, catID *CatID, data *ToyCreateRepo) error {
	ret := _mock.Called(ctx, catID, data)

	if len(ret) == 0 {
		panic("no return value specified for ToyCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID, *ToyCreateRepo) error); ok {
		r0 = returnFunc(ctx, catID, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_ToyCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToyCreate'
type MockCatRepositoryInterface_ToyCreate_Call struct {
	*mock.Call
}

// ToyCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *CatID
//   - data *ToyCreateRepo
func (_e *MockCatRepositoryInterface_Expecter) ToyCreate(ctx interface{}, catID interface{}, data interface{}) *MockCatRepositoryInterface_ToyCreate_Call {
	return &MockCatRepositoryInterface_ToyCreate_Call{Call: _e.mock.On("ToyCreate", ctx, catID, data)}
}

func (_c *MockCatRepositoryInterface_ToyCreate_Call) Run(run func(ctx context.Context, catID *CatID, data *ToyCreateRepo)) *MockCatRepositoryInterface_ToyCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		var arg2 *ToyCreateRepo
		if args[2] != nil {
			arg2 = args[2].(*ToyCreateRepo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_ToyCreate_Call) Return(err error) *MockCatRepositoryInterface_ToyCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_ToyCreate_Call) RunAndReturn(run func(ctx context.Context, catID *CatID, data *ToyCreateRepo) error) *MockCatRepositoryInterface_ToyCreate_Call {
	_c.Call.Return(run)
	return _c
}

// ToyDelete provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) ToyDelete(ctx context.Context, toyID *ToyID) error {
	ret := _mock.Called(ctx, toyID)

	if len(ret) == 0 {
		panic("no return value specified for ToyDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ToyID) error); ok {
		r0 = returnFunc(ctx, toyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_ToyDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToyDelete'
type MockCatRepositoryInterface_ToyDelete_Call struct {
	*mock.Call
}

// ToyDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - toyID *ToyID
func (_e *MockCatRepositoryInterface_Expecter) ToyDelete(ctx interface{}, toyID interface{}) *MockCatRepositoryInterface_ToyDelete_Call {
	return &MockCatRepositoryInterface_ToyDelete_Call{Call: _e.mock.On("ToyDelete", ctx, toyID)}
}

func (_c *MockCatRepositoryInterface_ToyDelete_Call) Run(run func(ctx context.Context, toyID *ToyID)) *MockCatRepositoryInterface_ToyDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ToyID
		if args[1] != nil {
			arg1 = args[1].(*ToyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_ToyDelete_Call) Return(err error) *MockCatRepositoryInterface_ToyDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_ToyDelete_Call) RunAndReturn(run func(ctx context.Context, toyID *ToyID) error) *MockCatRepositoryInterface_ToyDelete_Call {
	_c.Call.Return(run)
	return _c
}

// ToyExists provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) ToyExists(ctx context.Context, id *ToyID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToyExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ToyID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_ToyExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToyExists'
type MockCatRepositoryInterface_ToyExists_Call struct {
	*mock.Call
}

// ToyExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id *ToyID
func (_e *MockCatRepositoryInterface_Expecter) ToyExists(ctx interface{}, id interface{}) *MockCatRepositoryInterface_ToyExists_Call {
	return &MockCatRepositoryInterface_ToyExists_Call{Call: _e.mock.On("ToyExists", ctx, id)}
}

func (_c *MockCatRepositoryInterface_ToyExists_Call) Run(run func(ctx context.Context, id *ToyID)) *MockCatRepositoryInterface_ToyExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ToyID
		if args[1] != nil {
			arg1 = args[1].(*ToyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_ToyExists_Call) Return(err error) *MockCatRepositoryInterface_ToyExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_ToyExists_Call) RunAndReturn(run func(ctx context.Context, id *ToyID) error) *MockCatRepositoryInterface_ToyExists_Call {
	_c.Call.Return(run)
	return _c
}

// ToySearch provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) ToySearch(ctx context.Context, catID *CatID, params *ToySearchParams) ([]*Toy, error) {
	ret := _mock.Called(ctx, catID, params)

	if len(ret) == 0 {
		panic("no return value specified for ToySearch")
	}

	var r0 []*Toy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID, *ToySearchParams) ([]*Toy, error)); ok {
		return returnFunc(ctx, catID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID, *ToySearchParams) []*Toy); ok {
		r0 = returnFunc(ctx, catID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Toy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *CatID, *ToySearchParams) error); ok {
		r1 = returnFunc(ctx, catID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatRepositoryInterface_ToySearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToySearch'
type MockCatRepositoryInterface_ToySearch_Call struct {
	*mock.Call
}

// ToySearch is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *CatID
//   - params *ToySearchParams
func (_e *MockCatRepositoryInterface_Expecter) ToySearch(ctx interface{}, catID interface{}, params interface{}) *MockCatRepositoryInterface_ToySearch_Call {
	return &MockCatRepositoryInterface_ToySearch_Call{Call: _e.mock.On("ToySearch", ctx, catID, params)}
}

func (_c *MockCatRepositoryInterface_ToySearch_Call) Run(run func(ctx context.Context, catID *CatID, params *ToySearchParams)) *MockCatRepositoryInterface_ToySearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		var arg2 *ToySearchParams
		if args[2] != nil {
			arg2 = args[2].(*ToySearchParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_ToySearch_Call) Return(toys []*Toy, err error) *MockCatRepositoryInterface_ToySearch_Call {
	_c.Call.Return(toys, err)
	return _c
}

func (_c *MockCatRepositoryInterface_ToySearch_Call) RunAndReturn(run func(ctx context.Context, catID *CatID, params *ToySearchParams) ([]*Toy, error)) *MockCatRepositoryInterface_ToySearch_Call {
	_c.Call.Return(run)
	return _c
}
