// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cat

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCatRepositoryInterface creates a new instance of MockCatRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatRepositoryInterface {
	mock := &MockCatRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatRepositoryInterface is an autogenerated mock type for the CatRepositoryInterface type
type MockCatRepositoryInterface struct {
	mock.Mock
}

type MockCatRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatRepositoryInterface) EXPECT() *MockCatRepositoryInterface_Expecter {
	return &MockCatRepositoryInterface_Expecter{mock: &_m.Mock}
}

// AddToy provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) AddToy(ctx context.Context, catID *CatID, data *CreateToyRepo) error {
	ret := _mock.Called(ctx, catID, data)

	if len(ret) == 0 {
		panic("no return value specified for AddToy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID, *CreateToyRepo) error); ok {
		r0 = returnFunc(ctx, catID, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_AddToy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToy'
type MockCatRepositoryInterface_AddToy_Call struct {
	*mock.Call
}

// AddToy is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *CatID
//   - data *CreateToyRepo
func (_e *MockCatRepositoryInterface_Expecter) AddToy(ctx interface{}, catID interface{}, data interface{}) *MockCatRepositoryInterface_AddToy_Call {
	return &MockCatRepositoryInterface_AddToy_Call{Call: _e.mock.On("AddToy", ctx, catID, data)}
}

func (_c *MockCatRepositoryInterface_AddToy_Call) Run(run func(ctx context.Context, catID *CatID, data *CreateToyRepo)) *MockCatRepositoryInterface_AddToy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		var arg2 *CreateToyRepo
		if args[2] != nil {
			arg2 = args[2].(*CreateToyRepo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_AddToy_Call) Return(err error) *MockCatRepositoryInterface_AddToy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_AddToy_Call) RunAndReturn(run func(ctx context.Context, catID *CatID, data *CreateToyRepo) error) *MockCatRepositoryInterface_AddToy_Call {
	_c.Call.Return(run)
	return _c
}

// CatExists provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) CatExists(ctx context.Context, id *CatID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CatExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_CatExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatExists'
type MockCatRepositoryInterface_CatExists_Call struct {
	*mock.Call
}

// CatExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id *CatID
func (_e *MockCatRepositoryInterface_Expecter) CatExists(ctx interface{}, id interface{}) *MockCatRepositoryInterface_CatExists_Call {
	return &MockCatRepositoryInterface_CatExists_Call{Call: _e.mock.On("CatExists", ctx, id)}
}

func (_c *MockCatRepositoryInterface_CatExists_Call) Run(run func(ctx context.Context, id *CatID)) *MockCatRepositoryInterface_CatExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_CatExists_Call) Return(err error) *MockCatRepositoryInterface_CatExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_CatExists_Call) RunAndReturn(run func(ctx context.Context, id *CatID) error) *MockCatRepositoryInterface_CatExists_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeStatus provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) ChangeStatus(ctx context.Context, id *CatID, status *CatStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for ChangeStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID, *CatStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_ChangeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeStatus'
type MockCatRepositoryInterface_ChangeStatus_Call struct {
	*mock.Call
}

// ChangeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id *CatID
//   - status *CatStatus
func (_e *MockCatRepositoryInterface_Expecter) ChangeStatus(ctx interface{}, id interface{}, status interface{}) *MockCatRepositoryInterface_ChangeStatus_Call {
	return &MockCatRepositoryInterface_ChangeStatus_Call{Call: _e.mock.On("ChangeStatus", ctx, id, status)}
}

func (_c *MockCatRepositoryInterface_ChangeStatus_Call) Run(run func(ctx context.Context, id *CatID, status *CatStatus)) *MockCatRepositoryInterface_ChangeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		var arg2 *CatStatus
		if args[2] != nil {
			arg2 = args[2].(*CatStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_ChangeStatus_Call) Return(err error) *MockCatRepositoryInterface_ChangeStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_ChangeStatus_Call) RunAndReturn(run func(ctx context.Context, id *CatID, status *CatStatus) error) *MockCatRepositoryInterface_ChangeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) Create(ctx context.Context, data *CreateCatRepo) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CreateCatRepo) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCatRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data *CreateCatRepo
func (_e *MockCatRepositoryInterface_Expecter) Create(ctx interface{}, data interface{}) *MockCatRepositoryInterface_Create_Call {
	return &MockCatRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockCatRepositoryInterface_Create_Call) Run(run func(ctx context.Context, data *CreateCatRepo)) *MockCatRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CreateCatRepo
		if args[1] != nil {
			arg1 = args[1].(*CreateCatRepo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_Create_Call) Return(err error) *MockCatRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, data *CreateCatRepo) error) *MockCatRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) Delete(ctx context.Context, id *CatID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCatRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id *CatID
func (_e *MockCatRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockCatRepositoryInterface_Delete_Call {
	return &MockCatRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCatRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id *CatID)) *MockCatRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_Delete_Call) Return(err error) *MockCatRepositoryInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, id *CatID) error) *MockCatRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteToy provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) DeleteToy(ctx context.Context, toyID *ToyID) error {
	ret := _mock.Called(ctx, toyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteToy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ToyID) error); ok {
		r0 = returnFunc(ctx, toyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_DeleteToy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteToy'
type MockCatRepositoryInterface_DeleteToy_Call struct {
	*mock.Call
}

// DeleteToy is a helper method to define mock.On call
//   - ctx context.Context
//   - toyID *ToyID
func (_e *MockCatRepositoryInterface_Expecter) DeleteToy(ctx interface{}, toyID interface{}) *MockCatRepositoryInterface_DeleteToy_Call {
	return &MockCatRepositoryInterface_DeleteToy_Call{Call: _e.mock.On("DeleteToy", ctx, toyID)}
}

func (_c *MockCatRepositoryInterface_DeleteToy_Call) Run(run func(ctx context.Context, toyID *ToyID)) *MockCatRepositoryInterface_DeleteToy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ToyID
		if args[1] != nil {
			arg1 = args[1].(*ToyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_DeleteToy_Call) Return(err error) *MockCatRepositoryInterface_DeleteToy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_DeleteToy_Call) RunAndReturn(run func(ctx context.Context, toyID *ToyID) error) *MockCatRepositoryInterface_DeleteToy_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) GetByID(ctx context.Context, id *CatID) (*Cat, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *Cat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID) (*Cat, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID) *Cat); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Cat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *CatID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCatRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id *CatID
func (_e *MockCatRepositoryInterface_Expecter) GetByID(ctx interface{}, id interface{}) *MockCatRepositoryInterface_GetByID_Call {
	return &MockCatRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCatRepositoryInterface_GetByID_Call) Run(run func(ctx context.Context, id *CatID)) *MockCatRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_GetByID_Call) Return(cat *Cat, err error) *MockCatRepositoryInterface_GetByID_Call {
	_c.Call.Return(cat, err)
	return _c
}

func (_c *MockCatRepositoryInterface_GetByID_Call) RunAndReturn(run func(ctx context.Context, id *CatID) (*Cat, error)) *MockCatRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetToyByID provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) GetToyByID(ctx context.Context, toyID *ToyID) (*Toy, error) {
	ret := _mock.Called(ctx, toyID)

	if len(ret) == 0 {
		panic("no return value specified for GetToyByID")
	}

	var r0 *Toy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ToyID) (*Toy, error)); ok {
		return returnFunc(ctx, toyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ToyID) *Toy); ok {
		r0 = returnFunc(ctx, toyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Toy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ToyID) error); ok {
		r1 = returnFunc(ctx, toyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatRepositoryInterface_GetToyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToyByID'
type MockCatRepositoryInterface_GetToyByID_Call struct {
	*mock.Call
}

// GetToyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - toyID *ToyID
func (_e *MockCatRepositoryInterface_Expecter) GetToyByID(ctx interface{}, toyID interface{}) *MockCatRepositoryInterface_GetToyByID_Call {
	return &MockCatRepositoryInterface_GetToyByID_Call{Call: _e.mock.On("GetToyByID", ctx, toyID)}
}

func (_c *MockCatRepositoryInterface_GetToyByID_Call) Run(run func(ctx context.Context, toyID *ToyID)) *MockCatRepositoryInterface_GetToyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ToyID
		if args[1] != nil {
			arg1 = args[1].(*ToyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_GetToyByID_Call) Return(toy *Toy, err error) *MockCatRepositoryInterface_GetToyByID_Call {
	_c.Call.Return(toy, err)
	return _c
}

func (_c *MockCatRepositoryInterface_GetToyByID_Call) RunAndReturn(run func(ctx context.Context, toyID *ToyID) (*Toy, error)) *MockCatRepositoryInterface_GetToyByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetToys provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) GetToys(ctx context.Context, catID *CatID) ([]*Toy, error) {
	ret := _mock.Called(ctx, catID)

	if len(ret) == 0 {
		panic("no return value specified for GetToys")
	}

	var r0 []*Toy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID) ([]*Toy, error)); ok {
		return returnFunc(ctx, catID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID) []*Toy); ok {
		r0 = returnFunc(ctx, catID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Toy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *CatID) error); ok {
		r1 = returnFunc(ctx, catID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatRepositoryInterface_GetToys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToys'
type MockCatRepositoryInterface_GetToys_Call struct {
	*mock.Call
}

// GetToys is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *CatID
func (_e *MockCatRepositoryInterface_Expecter) GetToys(ctx interface{}, catID interface{}) *MockCatRepositoryInterface_GetToys_Call {
	return &MockCatRepositoryInterface_GetToys_Call{Call: _e.mock.On("GetToys", ctx, catID)}
}

func (_c *MockCatRepositoryInterface_GetToys_Call) Run(run func(ctx context.Context, catID *CatID)) *MockCatRepositoryInterface_GetToys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_GetToys_Call) Return(toys []*Toy, err error) *MockCatRepositoryInterface_GetToys_Call {
	_c.Call.Return(toys, err)
	return _c
}

func (_c *MockCatRepositoryInterface_GetToys_Call) RunAndReturn(run func(ctx context.Context, catID *CatID) ([]*Toy, error)) *MockCatRepositoryInterface_GetToys_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) Search(ctx context.Context, params *CatSearchParams) ([]*Cat, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*Cat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatSearchParams) ([]*Cat, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatSearchParams) []*Cat); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Cat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *CatSearchParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatRepositoryInterface_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockCatRepositoryInterface_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - params *CatSearchParams
func (_e *MockCatRepositoryInterface_Expecter) Search(ctx interface{}, params interface{}) *MockCatRepositoryInterface_Search_Call {
	return &MockCatRepositoryInterface_Search_Call{Call: _e.mock.On("Search", ctx, params)}
}

func (_c *MockCatRepositoryInterface_Search_Call) Run(run func(ctx context.Context, params *CatSearchParams)) *MockCatRepositoryInterface_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatSearchParams
		if args[1] != nil {
			arg1 = args[1].(*CatSearchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_Search_Call) Return(cats []*Cat, err error) *MockCatRepositoryInterface_Search_Call {
	_c.Call.Return(cats, err)
	return _c
}

func (_c *MockCatRepositoryInterface_Search_Call) RunAndReturn(run func(ctx context.Context, params *CatSearchParams) ([]*Cat, error)) *MockCatRepositoryInterface_Search_Call {
	_c.Call.Return(run)
	return _c
}

// ToyBelongs provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) ToyBelongs(ctx context.Context, catID *CatID, toyID *ToyID) error {
	ret := _mock.Called(ctx, catID, toyID)

	if len(ret) == 0 {
		panic("no return value specified for ToyBelongs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CatID, *ToyID) error); ok {
		r0 = returnFunc(ctx, catID, toyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_ToyBelongs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToyBelongs'
type MockCatRepositoryInterface_ToyBelongs_Call struct {
	*mock.Call
}

// ToyBelongs is a helper method to define mock.On call
//   - ctx context.Context
//   - catID *CatID
//   - toyID *ToyID
func (_e *MockCatRepositoryInterface_Expecter) ToyBelongs(ctx interface{}, catID interface{}, toyID interface{}) *MockCatRepositoryInterface_ToyBelongs_Call {
	return &MockCatRepositoryInterface_ToyBelongs_Call{Call: _e.mock.On("ToyBelongs", ctx, catID, toyID)}
}

func (_c *MockCatRepositoryInterface_ToyBelongs_Call) Run(run func(ctx context.Context, catID *CatID, toyID *ToyID)) *MockCatRepositoryInterface_ToyBelongs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CatID
		if args[1] != nil {
			arg1 = args[1].(*CatID)
		}
		var arg2 *ToyID
		if args[2] != nil {
			arg2 = args[2].(*ToyID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_ToyBelongs_Call) Return(err error) *MockCatRepositoryInterface_ToyBelongs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_ToyBelongs_Call) RunAndReturn(run func(ctx context.Context, catID *CatID, toyID *ToyID) error) *MockCatRepositoryInterface_ToyBelongs_Call {
	_c.Call.Return(run)
	return _c
}

// ToyExists provides a mock function for the type MockCatRepositoryInterface
func (_mock *MockCatRepositoryInterface) ToyExists(ctx context.Context, id *ToyID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToyExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ToyID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCatRepositoryInterface_ToyExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToyExists'
type MockCatRepositoryInterface_ToyExists_Call struct {
	*mock.Call
}

// ToyExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id *ToyID
func (_e *MockCatRepositoryInterface_Expecter) ToyExists(ctx interface{}, id interface{}) *MockCatRepositoryInterface_ToyExists_Call {
	return &MockCatRepositoryInterface_ToyExists_Call{Call: _e.mock.On("ToyExists", ctx, id)}
}

func (_c *MockCatRepositoryInterface_ToyExists_Call) Run(run func(ctx context.Context, id *ToyID)) *MockCatRepositoryInterface_ToyExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ToyID
		if args[1] != nil {
			arg1 = args[1].(*ToyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatRepositoryInterface_ToyExists_Call) Return(err error) *MockCatRepositoryInterface_ToyExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCatRepositoryInterface_ToyExists_Call) RunAndReturn(run func(ctx context.Context, id *ToyID) error) *MockCatRepositoryInterface_ToyExists_Call {
	_c.Call.Return(run)
	return _c
}
