// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package hello

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHelloRepositoryInterface creates a new instance of MockHelloRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelloRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelloRepositoryInterface {
	mock := &MockHelloRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHelloRepositoryInterface is an autogenerated mock type for the HelloRepositoryInterface type
type MockHelloRepositoryInterface struct {
	mock.Mock
}

type MockHelloRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelloRepositoryInterface) EXPECT() *MockHelloRepositoryInterface_Expecter {
	return &MockHelloRepositoryInterface_Expecter{mock: &_m.Mock}
}

// GetHelloMessage provides a mock function for the type MockHelloRepositoryInterface
func (_mock *MockHelloRepositoryInterface) GetHelloMessage(context1 context.Context) (*Message, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetHelloMessage")
	}

	var r0 *Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*Message, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *Message); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHelloRepositoryInterface_GetHelloMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHelloMessage'
type MockHelloRepositoryInterface_GetHelloMessage_Call struct {
	*mock.Call
}

// GetHelloMessage is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHelloRepositoryInterface_Expecter) GetHelloMessage(context1 interface{}) *MockHelloRepositoryInterface_GetHelloMessage_Call {
	return &MockHelloRepositoryInterface_GetHelloMessage_Call{Call: _e.mock.On("GetHelloMessage", context1)}
}

func (_c *MockHelloRepositoryInterface_GetHelloMessage_Call) Run(run func(context1 context.Context)) *MockHelloRepositoryInterface_GetHelloMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHelloRepositoryInterface_GetHelloMessage_Call) Return(message *Message, err error) *MockHelloRepositoryInterface_GetHelloMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockHelloRepositoryInterface_GetHelloMessage_Call) RunAndReturn(run func(context1 context.Context) (*Message, error)) *MockHelloRepositoryInterface_GetHelloMessage_Call {
	_c.Call.Return(run)
	return _c
}
